- prototype.py
> New prototype version

- scraper/departements.py
- scraper/prototype.py
- setup.cfg
- tests/test_scrape.py
Réorganisation du code pour :
* Isoler le code qui gère les départements (on va possiblement en avoir besoin pour Maiia et Keldoc aussi ?)
* Rajoute différents commentaires dessus basé sur ma compréhension nouvelle des codes INSEE 😄 
* Ajout de tests unitaires sur ce code-là (avec des doctests)
NOTE : pour lancer le proto, il faut maintenant lancer `python scraper/prototype.py` (au lieu de `python prototype.py`). Le `scrape.py` à la racine ne bouge pas mais une PR suivante pourra le transformer en `scraper/__main__.py` par ex.
> Reorganize code, isolate and test departement code

- scraper/doctolib.py
- scraper/keldoc.py
- scraper/maiia.py
- scraper/prototype.py
Ajoute un module par site web.
> One module per website: doctolib, keldoc, maiia

- .github/workflows/scrape.yml
Ajout d'un job permettant de commit les changements et de push sur la branche 'data-auto'.
> GitHub Actions : push des données sur data-auto

- scraper/keldoc.py
Based on suggestions in https://github.com/CovidTrackerFr/vitemadose/pull/12
> Added 'requests' debug + check if appointments are closed

- scraper/doctolib.py
> Fix Tor Requests session setup

- scraper/doctolib.py
- tests/fixtures/doctolib/category-availabilities.json
- tests/fixtures/doctolib/category-booking.json
- tests/test_doctolib.py
Corrige une régression introduite par #17 
J'ai ajouté un test (qui pète actuellement sur `main`) pour bien vérifier qu'on a le comportement attendu.
> Fix category handling

- scraper/prototype.py
Several queries have been optimized in the scraping of available appointments in Keldoc script, the execution time is faster.
I think we can put Keldoc back.
> Bring back Keldoc scraper

- scraper/keldoc/keldoc_center.py
> Hotfix set not subscriptable [Keldoc]

- scraper/prototype.py
Classer les centres qui ont des rendez-vous plus proches que d'autres
> Sort appointment by date

- scraper/doctolib.py
- tests/test_doctolib.py
Closes #45 
Merci @aureliancnx !
> Fix special practice_id case

- scraper/doctolib.py
- scraper/maiia.py
- scraper/prototype.py
- utils/vmd_logger.py
I don't use Python's logging tools a lot, but I checked a bit how it works so I added some message formatting.
If you have any suggestions please feel free to ask or contribute.
Tested on the scraper CI (without autopush)
> Add a logger for the scraper

- scraper/ordoclic.py
+ removed trailing spaces
+ PEP8 E302 coding style
> Using logger for Ordoclic scraper

- scraper/scraper.py
Les URL doctolib sont mises en minuscules
> Fixes issue #55

- scraper/maiia.py
Reverts CovidTrackerFr/vitemadose#62
> Revert "Maiia parsing fixes & improvements"

- .gitlab-ci.yml
- gitlab-runner/.gitignore
- gitlab-runner/Vagrantfile
- gitlab-runner/deploy-dev-runner.sh
Avec des tous beaux runners sur OVH !
> Scrapping et Publication des JSON via Gitlab.com (CI + Pages)

- scraper/departements.py
- scraper/pattern/center_info.py
- setup.py
- utils/vmd_utils.py
En préparation à la recherche par ville (#120), ajout de la ville dans le json, de manière moins idiote qu'au dessus
> Préparation à la recherche par ville v2

- README.md
Je pense qu'avoir le max d'infos dans le Github pour une première contribution permettra d'onboard les nouveaux le plus efficacement. Vu à quel point on communique sur Telegram, cela mérite d'être directement sur cette page :)
> Ajouter quelques infos dans le README github

- scraper/mapharma/mapharma.py
J'avais bougé le doc de l'insee dans `data/output` sur ma branche locale et dans le code ... Je viens de re-test et le make passe.
> [Fix] Workflow scrape mypharma

- .github/workflows/mapharma_center_scrap.yml
Le dernier workflow a planté après 1.5h de scrap... Désolé ...
> Corrected wrong path in mapharma workflow

- scraper/doctolib/doctolib.py
- scraper/keldoc/keldoc.py
- scraper/maiia.py
- scraper/mapharma/mapharma.py
- scraper/ordoclic.py
- scraper/profiler.py
- scraper/scraper.py
- setup.py
Le plus complexe est la partie Queue en multiprocess pour suivre le bouzin, je suis pas certain d'avoir tout bien fait comme il faut donc s'il y a un expert, c'est top
> Collecte des stats sur les temps de scrapping par plateforme et par centre

- scraper/scraper.py
- tests/test_scraper.py
> #168 Ne pas mentionner un centre avec 0 dose comme disponible

- tests/test_departement.py
- utils/vmd_utils.py
Améliorations diverses de `get_city()` (cf. les messages de commits).
Ajout de tous les tests unitaires pour `departementUtils` (histoire de me faire la main avant ordoclic). On gagne 1% de coverage global :partying_face:
> departementUtils : ajout de tests unitaires et amélioration get_city()

- scraper/pattern/center_info.py
Je vais essayer de debug tout ce qu'on a comme bugs actuellement au niveau du scrap des centres. Avoir le message d'erreur ici m'aidera :)
> Ajout du message d'erreur dans les logs de  center_info.py

- data/output/maiia_centers.json
- scraper/maiia/maiia.py
- scraper/scraper.py
Au lieu du csv. Pour rappel le fichier maiia_centers.json est remis à jour par l'action 'Maiia center scrap'
> uses maiia_centers.json

- scraper/doctolib/doctolib_filters.py
- tests/test_doctolib.py
@Maijin avait ajouté des catégories dans #214 , mais la correction n'était pas bien faite à cause du stemming effectué au niveau de la comparaison. Maintenant, je .lower() et .strip() tout, et le test passe :)
Devrait fix #216 selon mes tests
> Correctly comparing categories

- scraper/keldoc/keldoc_center.py
Fix pour l'issue : https://github.com/CovidTrackerFr/vitemadose/issues/200
- Déplacement du raise for status
- On garde la capture des timeout
- Ajout du raise des httpstatus, puisqu'on a remonté le raise for status.
Première PR pour moi ici, n'hésitez pas a me faire des retours.
> Keldoc fix #200: http error are correctly catched

- scraper/pattern/center_info.py
et ses futures fautes d'orthographe...
> Ajout vaccin Janssen

- scraper/maiia/maiia_center_scrap.py
> maiia: ignore centers with children

- scraper/doctolib/doctolib_filters.py
> Add missing category

- scraper/scraper.py
ajout temporaire de Keldoc dans la liste des centres à ne pas remonter du CSV. Comme il n'a pas d'iterator non plus, il ne sera pas traité
> Exclusion temporaire Keldoc Fix #273

- scraper/keldoc/keldoc.py
- scraper/keldoc/keldoc_filters.py
- scraper/pattern/center_info.py
- tests/test_doctolib.py
- tests/test_keldoc.py
- tests/test_scraper.py
Fixes #230 
J'ai aussi fait 2-3 petits refacto.
Draft car je dois ajouter des tests
> ARNm lorsque AZ et (+55 ans suite)

- scraper/doctolib/doctolib.py
- scraper/pattern/center_info.py
- scraper/pattern/scraper_request.py
- scraper/scraper.py
- utils/vmd_utils.py
Reverts CovidTrackerFr/vitemadose#267
> Revert "Calcul des disponibilités à 24h et 7j pour doctolib (implémentation #265)"

- scraper/keldoc/keldoc.py
- scraper/keldoc/keldoc_filters.py
- scraper/pattern/center_info.py
- tests/test_doctolib.py
- tests/test_keldoc.py
- tests/test_scraper.py
Reverts CovidTrackerFr/vitemadose#260
> Revert "ARNm lorsque AZ et (+55 ans suite)"

- scraper/doctolib/doctolib.py
- scraper/pattern/center_info.py
- scraper/pattern/scraper_request.py
- scraper/scraper.py
- utils/vmd_utils.py
Reverts CovidTrackerFr/vitemadose#281
> Revert "Calcul des disponibilités à 24h et 7j pour doctolib (implémentation #265) suite revert"

- scraper/keldoc/keldoc.py
- scraper/keldoc/keldoc_filters.py
- scraper/pattern/center_info.py
- tests/test_doctolib.py
- tests/test_keldoc.py
- tests/test_scraper.py
Reverts CovidTrackerFr/vitemadose#278
> Revert "Revert "ARNm lorsque AZ et (+55 ans suite)""

- scraper/scraper.py
suite au retour des lantences qui font échouer le scraper sur timeout
> Exclusion temporaire Keldoc

- data/input/map.svg
- stats_generation/stats_map.py
+ possibilité de fournir les labels de l'échelle
+ fix class mayotte
> [Maps] Création map_taux_rdv.svg

- scraper/scraper.py
Reverts CovidTrackerFr/vitemadose#285
> Revert "Exclusion temporaire Keldoc"

- scraper/maiia/maiia.py
- scraper/pattern/scraper_result.py
- tests/test_maiia.py
enhancement #265 #292  
```
"appointment_schedules": {
"1_days": 4,
"7_days": 16,
"28_days": 64,
"49_days": 256
}
```
> [Maiia] ajout appointment_schedules

- scraper/pattern/center_info.py
Mise en page.
`Vaccine.ARNM` n'est pas à la ligne.
`Vaccine.ARNM` est à la ligne.
***
*En vous remerciant...*
> fix(layout): Mise à la ligne VACCINES_NAMES

- scraper/keldoc/keldoc.py
- scraper/keldoc/keldoc_center.py
- tests/test_keldoc.py
enhancement #265 #292
```
"appointment_schedules": {
"1_days": 4,
"7_days": 16,
"28_days": 64,
"49_days": 256
}
```
> [Keldoc] ajout appointment_schedules

- scraper/pattern/center_info.py
JSON n'arrive pas à serializer l'enum, j'ajoute la classe str dans l'héritage
class Vaccine(str, Enum)
> [Maiia] fix #312

- stats_generation/stats_available_centers.py
Remplace: https://github.com/CovidTrackerFr/vitemadose/pull/242
> Ajout metadata "last_edit_date" pour stats.json

- stats_generation/stats_available_centers.py
Reverts CovidTrackerFr/vitemadose#298
> Revert "Ajout metadata "last_edit_date" pour stats.json"

- data/input/centers_blocklist.json
- scraper/pattern/center_info.py
- scraper/scraper.py
Pour #296, j'introduit une blocklist à partir des URLs. 
Pourquoi les urls ? car on les a directement dans le json et qu'ils sont encore plus facile à trouver que le gid, ou le internal id, et à priori moins à même de changer.
> Add blocklist

- scraper/doctolib/doctolib_filters.py
**Fixes #310**
Prend en compte motifs de vaccination évoqués dans l'issue avec tests, à savoir : 
- Vaccin COVID-19 - AstraZeneca (55 ans et plus)
- Injection unique vaccin COVID-19 (Janssen)
Merci d'avance pour la review
> [Doctolib] Fixes #310 : add relevant vaccination motiv

- data/input/centers_blocklist.json
Fix #319 
j'en profite pour ajouter quelques infos dans le json pour facilement tracer ces ajouts. La fonction de filtre n'utilise que le champ urm
> [Blocklist] Ajout Grande Pharmacie Marcadet

- scraper/ordoclic.py
```
"appointment_schedules": {
"1_days": 4,
"7_days": 16,
"28_days": 64,
"49_days": 256
}
```
- mise à jour du filtre 'reason' (suite à la mise à jour de l'API Ordoclic)
- ajout de la gestion d'erreur http
- ajout du nom du vaccin
- petites corrections
enhancement #265 #292
> [Ordoclic] ajout appointment_schedules

- scraper/mapharma/mapharma.py
- tests/test_mapharma.py
```
"appointment_schedules": {
"1_days": 4,
"7_days": 16,
"28_days": 64,
"49_days": 256
}
```
enhancement #265 #292
> [Mapharma] ajout appointment_schedules

- Makefile
- scraper/doctolib/doctolib_center_scrap.py
- scraper/doctolib/doctolib_filters.py
Fixes #271 
Voir [mon commentaire détaillé](https://github.com/CovidTrackerFr/vitemadose/issues/271#issuecomment-830915167) sur l'analyse du problème et l'approche abordée.
Preneur de vos avis / débat, c'est un filtre qui peut avoir beaucoup d'impacts je peux éventuellement fournir plus de chiffres où pousser l'analyse de l'impact plus loin.
> [Doctolib] Fixes #271, filtrer les centres vaccinant vraiment

- scraper/keldoc/keldoc_filters.py
- scraper/pattern/center_info.py
search vaccine name in motive category name if not found in motive name
Fix #328
> [Keldoc] get_vaccine_name fallback

- scraper/doctolib/doctolib.py
> [Doctolib] 🚨Urgent fix httpx client🚨

- scraper/maiia/maiia_utils.py
> [Maiia] reduce paged requests page size

- utils/vmd_utils.py
Hello, voici une petite réécriture toute bête pour régler le soucis de manière compatible avec ma modification précédente.
@Maijin il faudra relancer le doctolib_center_scrap à la main par contre (ou atteindre le prochain lancement) pour mettre à jour le fichier json des centres doctolib afin de récupérer les centres concernés !
> [Doctolib] Correction codes INSEE cedex

- data/input/cedex_to_insee.json
> [Doctolib] Correction codes postaux CEDEX et ajout dans json

- scraper/doctolib/doctolib_filters.py
> Add missing doctolib category

- scraper/doctolib/doctolib.py
related https://github.com/CovidTrackerFr/vitemadose/issues/334
> Fixed J&J vaccine appointments (doctolib.py)

- scraper/keldoc/keldoc_center.py
**Fixes #233**
Une seule ligne, mais qui doit avoir pas mal de conséquences 😬,  je pense que ce correctif va ajouter pas mal de doses :) 
Voir mon commentaire sur l'issue pour plus de détails : https://github.com/CovidTrackerFr/vitemadose/issues/233#issuecomment-833910345
> [Keldoc] Fixes #233 : centres sans rdv, correctif qui va ajouter bcp de doses

- scraper/pattern/center_info.py
` undefined name 'List' ` in `scraper/pattern/center_info.py:58`
> Added mising typing import

- stats_generation/stats_available_centers.py
- stats_generation/stats_center_types.py
- tests/test_stats.py
> Fixes #268

- stats_generation/stats_center_types.py
Change calculation method since the numbers are not the same if we compare results by plateforme and center type
> Fix center types stats calculation

- scraper/ordoclic.py
- tests/test_ordoclic.py
```
"appointment_schedules": [
{
"name": "chronodose",
"from": "2021-05-08T00:00:00+02:00",
"to": "2021-05-09T23:59:59+02:00",
"total": 42
},
{
"name": "1_days",
"from": "2021-05-08T00:00:00+02:00",
"to": "2021-05-08T23:59:59+02:00",
"total": 21
},
{
"name": "2_days",
"from": "2021-05-08T00:00:00+02:00",
"to": "2021-05-09T23:59:59+02:00",
"total": 42
},
{
"name": "7_days",
"from": "2021-05-08T00:00:00+02:00",
"to": "2021-05-14T23:59:59+02:00",
"total": 70
},
{
"name": "28_days",
"from": "2021-05-08T00:00:00+02:00",
"to": "2021-06-04T23:59:59+02:00",
"total": 280
},
{
"name": "49_days",
"from": "2021-05-08T00:00:00+02:00",
"to": "2021-06-25T23:59:59+02:00",
"total": 490
}
],
```
> [Ordoclic] 🕜 chronodoses

- scraper/mapharma/mapharma.py
- tests/test_mapharma.py
```
"appointment_schedules": [
{
"name": "chronodose",
"from": "2021-05-08T00:00:00+02:00",
"to": "2021-05-09T23:59:59+02:00",
"total": 42
},
{
"name": "1_days",
"from": "2021-05-08T00:00:00+02:00",
"to": "2021-05-08T23:59:59+02:00",
"total": 21
},
{
"name": "2_days",
"from": "2021-05-08T00:00:00+02:00",
"to": "2021-05-09T23:59:59+02:00",
"total": 42
},
{
"name": "7_days",
"from": "2021-05-08T00:00:00+02:00",
"to": "2021-05-14T23:59:59+02:00",
"total": 70
},
{
"name": "28_days",
"from": "2021-05-08T00:00:00+02:00",
"to": "2021-06-04T23:59:59+02:00",
"total": 280
},
{
"name": "49_days",
"from": "2021-05-08T00:00:00+02:00",
"to": "2021-06-25T23:59:59+02:00",
"total": 490
}
],
```
> [Mapharma] 🕜 chronodoses

- scraper/keldoc/keldoc_center.py
- tests/test_keldoc.py
```
"appointment_schedules": [
{
"name": "chronodose",
"from": "2021-05-08T00:00:00+02:00",
"to": "2021-05-09T23:59:59+02:00",
"total": 256
},
{
"name": "1_days",
"from": "2021-05-08T00:00:00+02:00",
"to": "2021-05-08T23:59:59+02:00",
"total": 128
},
{
"name": "2_days",
"from": "2021-05-08T00:00:00+02:00",
"to": "2021-05-09T23:59:59+02:00",
"total": 256
},
{
"name": "7_days",
"from": "2021-05-08T00:00:00+02:00",
"to": "2021-05-14T23:59:59+02:00",
"total": 512
},
{
"name": "28_days",
"from": "2021-05-08T00:00:00+02:00",
"to": "2021-06-04T23:59:59+02:00",
"total": 1024
},
{
"name": "49_days",
"from": "2021-05-08T00:00:00+02:00",
"to": "2021-06-25T23:59:59+02:00",
"total": 4096
}
],
```
> [Keldoc] 🕜 chronodoses

- scraper/maiia/maiia.py
- tests/test_maiia.py
```
"appointment_schedules": [
{
"name": "chronodose",
"from": "2021-05-08T00:00:00+02:00",
"to": "2021-05-09T23:59:59+02:00",
"total": 42
},
{
"name": "1_days",
"from": "2021-05-08T00:00:00+02:00",
"to": "2021-05-08T23:59:59+02:00",
"total": 21
},
{
"name": "2_days",
"from": "2021-05-08T00:00:00+02:00",
"to": "2021-05-09T23:59:59+02:00",
"total": 42
},
{
"name": "7_days",
"from": "2021-05-08T00:00:00+02:00",
"to": "2021-05-14T23:59:59+02:00",
"total": 70
},
{
"name": "28_days",
"from": "2021-05-08T00:00:00+02:00",
"to": "2021-06-04T23:59:59+02:00",
"total": 280
},
{
"name": "49_days",
"from": "2021-05-08T00:00:00+02:00",
"to": "2021-06-25T23:59:59+02:00",
"total": 490
}
],
```
> [Maiia] 🕜 chronodoses

- scraper/ordoclic.py
**Checklist**
juste prévoir le cas où search fait un timeout et renvoie None
> [Ordoclic] search error handling

- scraper/doctolib/doctolib.py
Correction d'une petite erreur sur les chronodoses
> [DOCTOLIB] CORRECTION CHRONODOSES

- scraper/doctolib/doctolib.py
- scraper/keldoc/keldoc_center.py
- scraper/maiia/maiia.py
- scraper/mapharma/mapharma.py
- scraper/ordoclic.py
- scraper/pattern/center_info.py
- scraper/pattern/scraper_result.py
- tests/test_ordoclic.py
- utils/vmd_utils.py
Centralisation des paramètres des chronodoses dans une list unique, afin de pouvoir changer les règles à la volée pour toutes les plateformes
> [CHRONODOSES] - Centralisation des paramètres

- scraper/scraper.py
J'ai ajouté une annotation type de réponse de la méthode fetch_centre_slots (-> ScraperResult) -> Vue avec Noé dans le but de faire cette PR (qui logiquement peut être validé)
> AJOUT ANNOTATION DE SORTIE FETCH_CENTRE_SLOTS

- scraper/export/export_merge.py
- tests/test_scraper.py
Reverts CovidTrackerFr/vitemadose#427
> Revert "#384 Export spécifique aux collectivités d'outre-mer"

- dev/model/department.py
- dev/model/schedule.py
- setup.py
- tests/dev/model/test_center.py
- tests/dev/model/test_schedule.py
- tests/fixtures/utils/info_centres.json
The intent of this folder is to have tools useful to explore the data and run checks.
Spin a REPL and start repling!
**Checklist**
J’ai ajouté des genres de dataclasses (Pydantic::DataModel) qui vérifient l’intégrité des données et qui permettent une meilleur developer experience que des dictionnaires.
J’ai rajouté un peu de sucre aussi, au niveau pour itérer intuitivement.
Le but ici est de proposer une interface «dev» pour ouvrir rapidement des fichiers et explorer les données.
**Exemple**
```python
>>> from dev.model import department
>>> departments = department.load_all()
>>> assert {
...     centre
...     for department_ in data.values()
...     for centre in department_
...     if len(centre.vaccine_type) > 1
... }
True
```
> Add a dev folder with tools

- scraper/doctolib/doctolib_center_scrap.py
Rajout du Header manquant dans une requete
**Checklist**
> [DOCTOLIB] Add Header in request

- config.json
> [Doctolib] - Ajout de motifs de vaccination manquants

- .pre-commit-config.yaml
**Checklist**
J'ai ajouté une config de pre-commit pour que ce soit plus simple d'appliquer `black` systématiquement.
> Configure pre-commit

- scraper/doctolib/doctolib_center_scrap.py
Reverts CovidTrackerFr/vitemadose#452
> Revert "[Doctolib Scraper] Améliorer le temps de scrape des centres"

- config.json
Ajout de la version accentuée du motif "Personnes éligibles"
> Doctolib - Ajout motives

- scraper/doctolib/doctolib_center_scrap.py
Reverts CovidTrackerFr/vitemadose#463
> Revert "Revert "[Doctolib Scraper] Améliorer le temps de scrape des centres""

- dev/model/department.py
- scraper/doctolib/conf.py
- scraper/doctolib/doctolib.py
- scraper/doctolib/doctolib_center_scrap.py
- scraper/export/export_merge.py
- scraper/export/export_pool.py
- scraper/keldoc/keldoc.py
- scraper/keldoc/keldoc_center.py
- scraper/keldoc/keldoc_filters.py
- scraper/maiia/maiia.py
- scraper/maiia/maiia_center_scrap.py
- scraper/main.py
- scraper/mapharma/mapharma.py
- scraper/opendata/opendata.py
- scraper/ordoclic.py
- scraper/pattern/center_info.py
- scraper/pattern/center_location.py
- scraper/pattern/scraper_request.py
- scraper/pattern/vaccine.py
- scraper/scraper.py
- tests/dev/model/test_center.py
- tests/test_center_info.py
- tests/test_center_location.py
- tests/test_doctolib.py
- tests/test_doctolib_scraper.py
- tests/test_mapharma.py
- tests/test_ordoclic.py
- tests/test_scraper.py
- utils/vmd_logger.py
**Checklist**
En lisant le code, j’ai vu plusieurs aspects que je pouvais simplifier/réorganiser.
La plupart des changements sont triviaux (formatting, unused imports).
> Various cleanups

- dev/quality_checks.py
**Checklist**
Ajoute un script (extensible) qui valide plusieurs règles sur les données pour vérifier leur intégrité.
```shell
python3 dev/quality_checks.py
```
Définir la fonction qui valide l’élément et l’ajouter à la liste de vérifications en fonction de l’élément vérifié.
(Soit `department_checks` soit `center_checks`)
> Add a script to run quality checks on data

- .pre-commit-config.yaml
**Checklist**
Je voudrais mettre à jour la version d'autoflake car l'argument `--ignore-init-module-imports` n'existe pas dans la version 1.1
> Upgrade autoflake in pre-commit

- scraper/doctolib/doctolib_center_scrap.py
**Checklist**
Refact de l'utilisation de la config de doctolib center scraper en utilisant DoctolibConf (déjà utilisée dans le scraper principal).
> Refact Doctolib center scraper config

- scraper/maiia/maiia.py
- tests/test_maiia.py
**Checklist**
J'ai ajouté un paramètre dans `center_iterator` pour ne pas générer le fichier maiia_centers quand on lance les tests.
> Maiia tests without overwriting data file

- scraper/scraper.py
Mise en pause temporaire de la plateforme le temps de voir avec eux quels sont les centres à afficher
> [AvecMonDoc] Mise en pause

- scraper/circuit_breaker.py
- scraper/keldoc/keldoc.py
- scraper/keldoc/keldoc_center.py
- scraper/scraper.py
- setup.py
- tests/test_circuit_breaker.py
- tests/test_keldoc.py
> Mettre Keldoc au coin quand il ne répond pas assez rapidement 🦆

- config.json
- scraper/manual/manual_urls.py
- scraper/scraper.py
- scraper/sheets.py
- tests/test_sheets.py
- Revert "Revert "Continuation de #438""
- Fix sheets scraper and configure the URL
**Checklist**
**Changes**
Le format parsé n’était pas bon, il retournait un dictionnaire de listes et non pas une liste de dictionnaires.
La spreadsheet de production est aussi configurée.
> Finish the manual inputs iterator

- .github/workflows/test.yml
- .gitignore
- .gitlab-ci.yml
- contributors.py
- scripts/contributors
- setup.py
**Checklist**
Génère une première mouture d'une ressource regroupant les contributeurs par dépôt git (scrap, web, ios, android, infra) et aussi tout ensemble. Les informations remontées sont celles connues de Github, du coup, mettez vos profils à jours.
> Génère une liste des contributeurs Github

- scraper/avecmondoc/avecmondoc.py
- scraper/circuit_breaker.py
- scraper/doctolib/doctolib.py
- scraper/doctolib/doctolib_center_scrap.py
- scraper/keldoc/keldoc.py
- scraper/keldoc/keldoc_center.py
- scraper/maiia/maiia.py
- scraper/mapharma/mapharma.py
- scraper/ordoclic.py
- scraper/pattern/scraper_result.py
- scraper/profiler.py
- scraper/scraper.py
**Checklist**
J'ai ajouté le pourcentage de centres qui n'ont pas de prochaine disponibilité dans le profiler du scraper.
> Ratio of None results to scraper profiler

- scraper/doctolib/doctolib.py
- tests/test_doctolib.py
Fixes #512 
**Checklist**
Voir mon analyse complète sur le ticket : https://github.com/CovidTrackerFr/vitemadose/issues/512#issuecomment-850908372
Ces changement peuvent avoir un impact non négligeable sur le scraping mais devraient refléter plus la réalité des RDV accessibles réellement via le site web de doctolib.
> [Doctolib] scraper par vaccins

- scraper/doctolib/doctolib.py
- tests/test_doctolib.py
Reverts CovidTrackerFr/vitemadose#529
> Revert "[Doctolib] scraper par vaccins"

- scraper/mapharma/mapharma.py
**Checklist**
Il y avait du code qui essaye de compter les requêtes alors que cet objet n'est pas disponible à ce moment-là.
> [MaPharma] Meilleure gestion des erreurs lorsque mapharma est indisponible

- scraper/doctolib/doctolib.py
- tests/test_doctolib.py
**Checklist**
MAJ de #529 avec 2 lignes d'update pour prendre en compte ce qui avait bougé entre le dev et le merge.
Voir mon analyse complète sur le ticket : https://github.com/CovidTrackerFr/vitemadose/issues/512#issuecomment-850908372
Ces changement peuvent avoir un impact non négligeable sur le scraping mais devraient refléter plus la réalité des RDV accessibles réellement via le site web de doctolib.
> [Doctolib] scraper par vaccins (MAJ)

- scraper/doctolib/doctolib.py
- scraper/scraper.py
> [Doctolib] Suite #543, correction des logs et gestion d'un cas supplémentaire

- scraper/doctolib/doctolib.py
- tests/test_doctolib.py
> [Doctolib] Suite #543 v3, correction d'un bug pour les pid en establishment-xxx

- data/input/insee_to_codepostal_and_code_departement.json
Ajout d'un code insee secondaire manquant
> [Maiie] ajout code insee secondaire sucy en brie 94

- config.json
- tests/test_scraper.py
Après une analyse des données, j'ai décidé de modifier les mots clés. Ce set de mot clé semble inclure tous les centres réservés sans bloquer des centres par erreur !
> [Centres réservés] - Modifications critères (avec tests)

- config.json
- scraper/doctolib/doctolib.py
- scraper/error.py
**Checklist**
A travers #535 j'ai compris qu'on ignorait les vaccins de type "injection unique" pour ceux ayant eu la covid, à cause du first_shot_motive=false
Au passage, j'ai encore affiné le tri des PID pour virer les "faux centres"
> [Doctolib] Correction filtre injection unqiue et modification gestion PID

- scraper/doctolib/doctolib.py
- scraper/scraper.py
> [Scraper Issue] - Add breakpoints to understand the issue

- scraper/doctolib/doctolib.py
Test pour régler le soucis de scrape
> disable circuit breaker for doctolib

- scraper/doctolib/doctolib.py
- scraper/scraper.py
Les breakpoints utilisés pour résoudre le soucis de scrape peuvent être enlevés.
> Removing ugly breakpoints

- scraper/doctolib/doctolib_center_scrap.py
> [Suite #566] - Ajout d'un autre message d'erreur

- utils/vmd_logger.py
J'ai oublié de virer une ligne de début dans le logger
> [Mesoigner] - Restauration logger original

- scraper/mesoigner/mesoigner.py
- scraper/mesoigner/mesoigner_center_scrap.py
Modification du format de l'API key au vu de ce qui est autorisé par les variables gitlab
> [Mesoigner] - correction API key

- scraper/mesoigner/mesoigner_center_scrap.py
Pour éviter une exception, petite modification du code si impossible d'accéder à l'API
> [Mesoigner] - Modification du comportement en cas d'erreur

- scraper/mesoigner/mesoigner.py
> mesoigner changement url fichier des centres

- scraper/mesoigner/mesoigner.py
Je n'avais pas initialisé appointment_schedules vu la disparition des chronodoses, mais c'est nécessaire pour les stats.
> [Mesoigner] - ajout chronodoses à 0

- scraper/mesoigner/mesoigner.py
Passage de la forme list à la forme str pour éviter un plantage.
> [Mesoigner] - Correction du vaccin type

- tests/test_mesoigner.py
> [Mesoigner] - Correction test unitaire

- scraper/mesoigner/mesoigner.py
- tests/fixtures/mesoigner/mesoigner_center_info.json
- tests/test_mesoigner.py
> ajout tests unitaires mesoigner

- management_scripts/manage_blocklist.py
> [BlockList Manager] - Passage par nom et CP plutot qu'URL

- config.json
- data/input/centers_blocklist.json
- scraper/keldoc/keldoc_center_scrap.py
**Checklist**
Suite aux infos glanées chez keldoc, j'ai adapté l'algo de parsage des départements en rajoutant les départements étranges dans le conf.json
J'ai comparé à la main, je scrape bien tous les centres qui proposent des rvds dans le fichier data.gouv (les centres "aucun rdv disponible" ne sont pas renvoyés par le endpoint)
Bravo à @aureliancnx @gaelbenoit pour avoir écrit 90% de ce scraper
>  [Keldoc Center Scrap] - Modifications selon préconisations Keldoc

- config.json
- scraper/avecmondoc/avecmondoc.py
- tests/fixtures/avecmondoc/iterator_search_result.json
- tests/test_avecmondoc.py
Ajout de motifs de consultation et prise en compte du type de centre (pharmacie, généraliste)
**Checklist**
> [AvecMonDoc] Amélioration détection des motifs et types de centres

- config.json
- scraper/export/resource_centres.py
- scraper/export/resource_creneaux_quotidiens.py
- scraper/scraper.py
@aureliancnx voici la réparation promise :)
> Reparation iterateur par creneau

- config.json
- scraper/avecmondoc/avecmondoc.py
- scraper/doctolib/doctolib.py
- scraper/keldoc/keldoc.py
- scraper/keldoc/keldoc_center.py
- scraper/keldoc/keldoc_center_scrap.py
- scraper/maiia/maiia.py
- scraper/mapharma/mapharma.py
- scraper/mesoigner/mesoigner.py
- scraper/scraper.py
- tests/fixtures/keldoc/result-ain.json
- utils/vmd_utils.py
Activation du scraper Keldoc en remplacement de data gouv
> Activation Scraper Keldoc

- scraper/keldoc/keldoc.py
J'avais utilisé la version débug local.
> Suite #592 - correction keldoc center_iterator

- config.json
- scraper/export/export_v2.py
- scraper/keldoc/keldoc.py
- scraper/keldoc/keldoc_center.py
- scraper/keldoc/keldoc_center_scrap.py
- scraper/keldoc/keldoc_filters.py
- scraper/pattern/scraper_request.py
- scraper/scraper.py
- tests/fixtures/keldoc/cabinet-16913-centerinfo.json
- tests/fixtures/keldoc/result-ain.json
- tests/test_keldoc.py
- tests/test_keldoc_center_scrap.py
- 
@fcamblor @Floby voici la gestion de keldoc :)
> [Creneaux] - Add Keldoc gesture

- scraper/doctolib/doctolib.py
- tests/test_doctolib.py
**Checklist**
Les PIDs Doctolib ne finiront pas de nous surprendre :p
J'ai bon espoir que cette correction soit la derniere :)
> [Doctolib] - Fixing PIDs

- scraper/avecmondoc/avecmondoc.py
- scraper/creneaux/creneau.py
- scraper/doctolib/doctolib.py
- scraper/export/resource_centres.py
- scraper/keldoc/keldoc_filters.py
- scraper/maiia/maiia.py
- scraper/mesoigner/mesoigner.py
- scraper/pattern/tags.py
- scraper/scraper.py
- tests/test_avecmondoc.py
- tests/test_doctolib.py
- tests/test_resource_par_departement.py
> [Creneaux] - Ajout plateforme AvecMonDoc

- scraper/avecmondoc/avecmondoc.py
- scraper/export/resource_centres.py
- scraper/mapharma/mapharma.py
- tests/test_mapharma.py
> [Creneaux] - Ajout de Mapharma

- stats_generation/stats_available_centers.py
Reverts CovidTrackerFr/vitemadose#605
> Revert "[Creneaux] - correctif"

- stats_generation/stats_center_types.py
> correction en urgence stats

- utils/vmd_utils.py
> [Correction] - Petite erreur qui plante tout

- scraper/export/resource_centres.py
- utils/vmd_utils.py
> Correction nom vaccin

- config.json
- scraper/export/export_v2.py
- scraper/export/resource_centres.py
> [VMD FAIT DE L'OPEN DATA] - Recréation du fichier suite à MAJ créneaux

- config.json
- scraper/avecmondoc/avecmondoc.py
- scraper/doctolib/conf.py
- scraper/doctolib/doctolib.py
- scraper/keldoc/keldoc_center.py
- scraper/maiia/maiia.py
- scraper/mapharma/mapharma.py
- scraper/mesoigner/mesoigner.py
- scraper/ordoclic/ordoclic.py
- tests/test_avecmondoc.py
- tests/test_doctolib.py
Mutualisation d'un max. de paramètres de config qui étaient éclatés, et correction de quelques paramètres foireux (timeout hyper longs)
> [CONFIG] - Mutualisation et correction de paramètres de config

- scraper/pattern/tags.py
Suite à la décision du front de ne pas l'implémenter
> [Creneaux] - suppression tag preco18_25

- scraper/pattern/tags.py
Reverts CovidTrackerFr/vitemadose#618
> Revert "[Creneaux] - suppression tag preco18_25"

- .github/workflows/keldoc_center_scrap.yml
- .github/workflows/maiia_center_scrap.yml
- .github/workflows/mesoigner_center_scrap.yml
> [Keldoc, Maiia, Mesoigner] - Préparation harmonisation nom des json

- scraper/doctolib/doctolib.py
- scraper/keldoc/keldoc.py
- scraper/maiia/maiia.py
- scraper/mesoigner/mesoigner.py
Ajout d'un tag imprimé par le logger pour savoir si la requête vient du cache ou pas
> [Cache] - Ajout d'un flag pour cache

- scraper/avecmondoc/avecmondoc.py
- scraper/doctolib/doctolib.py
- scraper/keldoc/keldoc.py
- scraper/maiia/maiia.py
- scraper/maiia/maiia_utils.py
- scraper/mapharma/mapharma.py
- scraper/mesoigner/mesoigner.py
- scraper/ordoclic/ordoclic.py
Changement du répertoire pour matcher github
> [Cache] - Changing folder 

- scraper/avecmondoc/avecmondoc.py
- scraper/doctolib/doctolib.py
- scraper/keldoc/keldoc.py
- scraper/maiia/maiia.py
- scraper/maiia/maiia_utils.py
- scraper/mapharma/mapharma.py
- scraper/mesoigner/mesoigner.py
- scraper/ordoclic/ordoclic.py
Reverts CovidTrackerFr/vitemadose#626
> Revert "[Cache] - Changing folder "

- scraper/avecmondoc/avecmondoc.py
- scraper/doctolib/doctolib.py
- scraper/keldoc/keldoc.py
- scraper/maiia/maiia.py
- scraper/maiia/maiia_utils.py
- scraper/mapharma/mapharma.py
- scraper/mesoigner/mesoigner.py
- scraper/ordoclic/ordoclic.py
- tests/test_avecmondoc.py
- tests/test_keldoc.py
Reverts CovidTrackerFr/vitemadose#625
> Revert "[Cache] - Généralisation à toutes les requêtes"

- config.json
- scraper/export/export_v2.py
- scraper/scraper.py
- utils/vmd_logger.py
Les centres pour lesquels les requetes sont trop longues (configurable dans config.json) sont dorrénavent printées
> [Logger] - Adding too long requests printing

- scraper/export/export_v2.py
- utils/vmd_logger.py
> [Logger for long requests]  - sorting results

- scraper/doctolib/doctolib.py
Je pense que cette modification permettra de retrouver certains centres manquants !
> Doctolib - centres manquants

- .github/workflows/bimedoc_center_scrap.yml
- Makefile
- config.json
- scraper/bimedoc/bimedoc_center_scrap.py
- scraper/creneaux/creneau.py
- scraper/error.py
Je commence par push le center scrap pour générer un fichier et ensuite faire des tests sur le répertoire staging gitlab.
Les tests unitaires arriveront à ce moment, ils sont déjà écrits !
> [New Platform] - Bimedoc (part 1 - center scraper)

- scraper/bimedoc/bimedoc_center_scrap.py
**Checklist**
Correction du Scraper BImedoc qui plante
> [Bimedoc] - Correction Center Scrap

- scraper/pattern/tags.py
> [Creneaux] - Suppression tags

- config.json
- scraper/maiia/maiia_center_scrap.py
- scraper/maiia/maiia_utils.py
- tests/test_maiia.py
> [Maiia] - Patching center scrap

- scraper/pattern/vaccine.py
**Checklist**
Suite à signalement par cbihan sur mattermost, certains centres (exemple = https://www.doctolib.fr/vaccination-covid-19/la-brede/centre-de-vaccination-intercommunal-montesquieu?pid=practice-191000) proposent du Pfizer si ContreIndication à 2eme dose AstraZeneca. 
Le code reconnaissait le centre comme proposant du Astra, c'est fix !
> [Vaccin name] - Correction pour Doctolib

- config.json
- data/output/mapharma_open_data.json
- scraper/mapharma/mapharma.py
- tests/fixtures/mapharma/mapharma_open_data.json
> [Mapharma] - Correcting fallback not updating

- config.json
- scraper/doctolib/doctolib.py
- scraper/maiia/maiia.py
- scraper/maiia/maiia_center_scrap.py
- scraper/pattern/tags.py
- tests/test_doctolib.py
**Checklist**
Les fichiers creneaux_quotidiens.json de chaque dep. contiennent désormais des tags first_dose, second_dose, third_dose qui sont fonctionnels pour  Docto et Maiia.
Pour le moment le tag all ne contient que les 1ères doses en attendant le front et les autres plateformes.
@fcamblor c'est donc normal si all est "faux" !
> [3e dose] - ajout maiia et MEP doctolib

- config.json
- scraper/export/resource_creneaux_quotidiens.py
- scraper/maiia/maiia.py
- scraper/pattern/tags.py
- tests/test_resource_creneaux_quotidiens.py
@fcamblor voici ce que tu as demandé !
> [3e doses] - Adaptation tags à la demande du front

- scraper/doctolib/doctolib.py
- scraper/maiia/maiia.py
@fcamblor peux tu vérifier que le compte est mieux ?
> [Doctolib] - corrections 3e doses 

- scraper/maiia/maiia.py
- scraper/maiia/maiia_utils.py
**Checklist**
We don't trust the total response by the result, so we try to get until the result is smaller than the limit parameter
> fix: Fix way to get paged of maiia
