.github/workflows/scrape.yml

Corrige la programmation de la GitHub Action.
**Motivation**
Suite à #1 la GitHub Action devait tourner toutes les 10min mais aucun run ne s'est encore lancé.
**Autres détails**
`0/10` ne correspondait pas à ce à quoi je m'attendais, `*/10` semble être correct
Cf [crontab.guru](https://crontab.guru/#*/10_*_*_*_*):
> At every 10th minute.

Fix scrape job schedule syntax

---

data/input/departements-france.csv
prototype.py
requirements.txt

Plus refacto pour utiliser un pool d'executeurs
et paralléliser les recherches sur les centres

Export par départements dans les fichiers idoines

---

.github/workflows/test.yml
README.md
prototype.py
requirements.txt
scripts/test
tests/test_scrape.py

Vu https://github.com/CovidTrackerFr/vitemadose/pull/4#discussion_r606436869
* Ajoute `pytest` pour qu'on puisse commencer à ajouter des TU si besoin.
* Ajoute un workflow `test.yml` pour lancer les tests sur les PR et `main`, pour voir l'effet d'une PR.

Setup test suite

---

scraper/prototype.py

Sur le site web, lorsqu'il n'y a aucun créneaux disponibles pour la semaine sélectionnée, la date du prochain créneau disponible est affichée (la semaine suivante ou plus tard).
Cette PR récupère cette information (uniquement la date sans l'heure comme sur le site web).

Doctolib: get the slot on the next week.

---

scraper/prototype.py

19 centres utilisent une URL commençant par `https://www.doctolib.fr/`.
Pour ces URL, la variable `centre` est convertie en minuscule: `centre-de-vaccination-covid-19-stade-de-France` -> `centre-de-vaccination-covid-19-stade-de-france`
Pour les anciennes et les nouvelles URL, les espaces sont supprimés (parfois en début ou en fin d'URL)

Parse old doctolib URL

---

scraper/departements.py
scraper/prototype.py

Dans la branche `main`, un département non renseigné arrête entièrement le script (La `RuntimeError` est propagée jusqu'à la fonction `main`).
Exemple: le gid 2269 n'a pas de département, il est indiqué comme "en cours de déclaration" dans le nom.
Cette PR léve une `ValueError` qui est interceptée dans `prototype.py`

departements.py: Replace RuntimeError by ValueError

---

scraper/prototype.py

Exemple:
```
727 Doctolib         2021-04-22                       49    
1653 Autre                                             94    
1645 Autre                                             28    
388 Doctolib                                          34    
1680 Doctolib                                          78    
1709 Doctolib                                          62    
2237 Autre                                             90    
1718 Doctolib                                          89    
697 Doctolib         2021-04-07T16:20:00.000+02:00    73    
1549 Autre                                             75    
1186 Doctolib         2021-04-06T11:30:00.000+02:00    81    
1723 Doctolib                                          60    
509 Keldoc …
```

More readable output

---

requirements.txt
scraper/doctolib.py
tests/fixtures/doctolib/basic-availabilities.json
tests/fixtures/doctolib/basic-booking.json
tests/fixtures/doctolib/next-slot-availabilities.json
tests/fixtures/doctolib/next-slot-booking.json
tests/test_doctolib.py

Ajout de tests de l'intégration Doctolib :
* Refacto de l'implémentation pour qu'on puisse "swap" les appels à l'API réelle par autre chose. Je suis parti sur HTTPX et ses [`MockTransport`](https://www.python-httpx.org/advanced/#mock-transports) (d'expérience, avec Requests ça aurait été galère à faire de façon aussi élégante). J'ai gardé Requests pour le debugging Tor (le `.get()` de HTTPX et Requests sont compatibles pour notre use case), en follow-up on pourrait voir si `httpx-socks` fait le job.
* La refacto permet d'ajouter toute une batterie de tests : tests d'API avec un "mock transport" qui renvoie des réponses JSON prémâchées, et des TU pour la logique de parsing des réponses.

Add tests to Doctolib implementation

---

scraper/keldoc.py

Some API calls for three or four vaccination centers are very slow (sometimes more than 3 minutes). Instead of cutting off the possibility to retrieve data about centers on Keldoc, it would be better to put a request timeout. The execution time of Keldoc is more reasonable (30-40 seconds on my side) with a timeout.
However, Keldoc uses an unoptimized way to handle vaccination slots. Indeed, on some centers, it is sometimes necessary to make a dozen requests on the agendas because it is necessary to retrieve information from several sub-agendas (not listed on their site) which are attached to different medical teams, which can slow down the process.
Until a solution is found to retrieve the next available date information with fewer queries (if that is possible?), using a timeout will …

Temporary fix for Keldoc timeouts.

---

.github/workflows/scrape.yml

Désormais l'action est run à chaque commit sur data-auto (donc c'est une sorte de boucle infinie…). 
Pour ça j'ai dû utiliser un PAT que j'ai généré (une Action ne peut pas être triggered par une action effectuant un commit avec le token de GitHub).

Action : run en permanence

---

scraper/doctolib.py
tests/test_doctolib.py

Ajoute un test pour le "hot fix" ajouté via ce commit 4cbbf2d5fb5f0206222596aeaea139999577233f
La fonctionnalité est refactorée pour l'occasion.
Remarques :
* J'ai retiré l'attribut `self.selected_practice_id`, en fait `DoctolibSlots()` est instancié à chaque appel à `fetch_slots()` donc pas lieu de stocker un attribut (et je pense pas qu'on veuille vraiment réutiliser ça de toute façon, vu que ça change à chaque URL).
* J'ai isolé le traitement dans une fonction à part, sans changer le traitement, ensuite ajouté mes tests, le cas "Broken 1" était HS, en utilisant HTTPX j'arrive à couvrir tous les tests avec un code + lisible.
* J'ai résolu un autre bug potentiel : l'argument `practice_id` était remplacé par la variable de boucle du même nom ! D'où `practice_id_filter`.

Add test for practice_id filter

---

scraper/maiia.py
setup.py

Ajout du module `dateutils` afin de parser les dates renvoyées par maiia qui sont sous le format iso. C'est plus propre que le `datetime.strptime(availability['firstPhysicalStartDateTime'],
'%Y-%m-%dT%H:%M:%S.%fZ')` 
actuel.

Add dateuitls and isoparse

---

Makefile
scripts/coverage
scripts/test
setup.cfg
setup.py

Ajoute `coverage-py` au repo pour pouvoir afficher le coverage lors de l'exécution des tests
**Motivation**
Ça aidera pour tracker les "zones d'ombre" au niveau des tests. L'idée je pense serait d'avoir des tests fonctionnels qui couvrent déjà au moins ~80% du code (et affiner avec des TU ensuite, mais ça ça prendra + d'efforts, pas forcément rentable vu le rythme auquel on bouge).
**Notes**
```console
$ scripts/test
+ venv/bin/coverage run -m pytest
===================================================== test session starts =====================================================
platform darwin -- Python 3.9.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /Users/florimond/Developer/covidtracker-projects/vitemadose, configfile: setup.cfg
collected 11 items …
```

Add test coverage tooling

---

scraper/prototype.py
tests/test_prototype.py
tests/utils.py

Ajout d'un TU pour `export_data()`, qui est maintenant complètement couvert. :-)
Coverage mis à jour : `prototype.py` passe de 37% (#44) à 62% :tada:
```
Name                               Stmts   Miss  Cover   Missing
----------------------------------------------------------------
scraper/departements.py               19      2    89%   53, 76
scraper/doctolib.py                   90      9    90%   17-22, 29-30, 60, 67, 119, 161
scraper/keldoc/keldoc.py              25     14    44%   21-41
scraper/keldoc/keldoc_center.py       86     73    15%   16-23, 26-41, 44-56, 59-89, 92-120
scraper/keldoc/keldoc_filters.py      86     75    13%   23-30, 35-52, 56-75, 79-87, 91-120
scraper/maiia.py                      48     37    23%   15-27, 31-67, 71-79
scraper/prototype.py …
```

Add unit tests for export_data

---

scraper/prototype.py

Supprimer les espaces au début et de fin de chaîne sur les noms des caractères.
Exemple avec: 
```
"nom": "CH de Rodez H\u00f4pital Jacques Puel ",
```

prototype.py: trim whitespaces from center name

---

scraper/doctolib/doctolib.py
tests/test_doctolib.py

Doctolib préferait que l'on utilise l'User-Agent pour le moment, afin effectuer les requêtes chez eux, parce que le header en place causerait trop de problèmes pour la gestion de celui-ci.

Using User-Agent due to Doctolib technical limitations

---

Makefile
scraper/scraper.py
scripts/scrape
utils/vmd_logger.py

Fix issue #39
Permet de lancer le script avec uniquement quelques URL: 
`script/scrape "<URL>" "<URL>" ....`
Ou
`make scrape URL=...` (une seule URL).
Dans ce cas le log des requests HTTP est affiché.

Scrape one URL with more log

---

README.md

- Remplacement de mapharma.fr par mapharma.net (@Noezor a le revert un peu trop large :sweat_smile:)
- Utilisation de nos assets pour les images plutôt que de récupérer des liens "aléatoires"

Correction README

---

scraper/keldoc/keldoc.py
scraper/keldoc/keldoc_center.py

Dû au problème de certains centres qui n'ont pas de rendez-vous trouvés (cf. issue https://github.com/CovidTrackerFr/vitemadose/issues/161), j'ai fait une petite investigation sur le sujet, comme ça me paraissait étonnant qu'il y ait un souci avec Keldoc.
Après petite vérification, c'est bien la requête vers Keldoc qui timeout, parce que le centre de Toulouse (en l'occurrence c'est celui que j'ai testé) avait de nombreux agendas internes dans les données du centre, je présume que la requête est trop lourde à supporter pour Keldoc de vérifier pour 50 jours (aie, pas de caching de leur côté).
Du coup j'ai décidé d'augmenter le timeout et de baisser le nombre de jours à 21 (soit 3 semaines) afin d'être moins méchant vis-à-vis de leur API, et ça a l'air de faire baisser le temps de la …

Fixed Keldoc issues with several agendas (timeout)

---

scraper/mapharma/mapharma.py

Corrige https://github.com/CovidTrackerFr/vitemadose/issues/160
Après discussion avec des personnes travaillant chez Ma Pharma, un user agent personnalisé pourrait être intéressant pour identifier clairement le scraper ViteMaDose et éviter de ban les IPs de nos workers.
Variable à ajouter github/gitlab : MAPHARMA_API_KEY
cc @rozierguillaume

Added MaPharma User Agent

---

scraper/doctolib/doctolib_center_scrap.py
scraper/scraper.py
utils/vmd_utils.py

Avant, tous les centres sous le même PID étaient traités comme uniques. Ce fix devrait  maintenant correctement rediriger vers le bon centre lorsqu'il a un PID. Il devrait aussi bien indexer les mêmes centres à PIDs différents.
(Notre code devient un peu bordélique, il y a trop de fois les choses faites)

[Bugfix] Unicité basée sur les urls + garde les pids dans les URLS

---

scraper/doctolib/doctolib_center_scrap.py
scraper/scraper.py
tests/test_doctolib_scraper.py
utils/vmd_utils.py

It seems to yield more (all ?) centers (@grubounet)
Because of this, I removed dependence on opendata for doctolib, which should remove the duplicates on the site.
The scraping is slow (10+mn). It can be sped-up with multithreading. I'll let @grubounet add a PR on top of this.
CC @tlevillayer with whom we investigated

Scrapping doctolib centers through departments

---

tests/test_maiia.py

le test va chercher une vraie dispo, donc quand fetch_slots trouve quelque chose, le test échoue... J'ai également forcé l'utf8 dans open car il y a un caractère unicode dans la fixture

Fix test_maiia.py

---

scraper/scraper.py

Pour aider à la migration des plateformes utilisant le csv vers un mode api (on cherche les centres directement sur les api de la plateforme et plus dans le csv), j'ai repris l'exclusion doctolib pour pouvoir ajouter des plateformes dans cette exclusion.
Il suffira donc d'ajouter un nom de plateforme (dans les faits la partie reconnaissable de son url) dans la liste plateformes_hors_csv

scraper.py -> use platform list to avoid csv

---

scraper/mapharma/mapharma.py

si la campagne contient 'total_libres' à 0, l'iterator ne renvoi pas de centre

issue #190

---

scraper/doctolib/doctolib.py
tests/test_doctolib.py

La logique précédent était un peu bancale et prennait tous les motifs possibles. Du coup, si un motif était présent dans la lsite des motifs pour un agenda, cet agenda était compté pour tous les motifs. En pratique, certains agendas ne sont disponnibles que pour certains motifs.
Corrige #215

Considère les agendas et pids pour un unique motif

---

scraper/mapharma/mapharma.py

LE responsable de mapharma vient de me remonter un problème de pharmacies qui n'apparaissent pas alors qu'elles ont des dispos. Le problème vient de l'intitulé de la campagne, mon seul moyen de faire la différence entre une campagne qui fait vraiment des vaccins et une campagne pour un autre sujet. Au lieu de comparer le nom complet de la campagne par rapport à mon filtre, je vais maintenant identifier des mots clés (injection covid) et aussi refuser les campagnes contenant certains mots clés (test antigénique)

Modification du filtre campagnes

---

scraper/maiia/maiia.py

petit problème de format de date passé à l'API maiia, du coup lorsque qu'un calendrier n'a de slots que dans plus d'une semaine, l'appel à availability-closests échoue et le scrap remonte 0 dispo

Fix maiia.py

---

scraper/ordoclic.py

retrait du filtre in.covidOnlineBookingAvailabilities.covidInjection1 qui semble ne plus fonctionner avec la dernière mise à jour de l'API Ordoclic, la recherche ne renvoie plus aucun centre si on active ce filtre
Resolve #256

Ordoclic: Fix #256 (plus aucun centre ne remonte)

---

scraper/mapharma/mapharma.py
tests/fixtures/mapharma/mapharma_open_data.json
tests/test_mapharma.py

j'ai corrigé le fallback opendata de mapharma. L'idée de ce fallback est d'utiliser la dernière version sauvegardée si l'API opendata ne répond pas. Le fallback allait chercher un fichier dans data/output mais en fait doit aller le chercher sur la branche data-auto
J'en ai profité pour ajouter des shims supplémentaires pour les tests unitaires qui étaient un peu faussés (enfin un peu sur le live en fait)

mapharma corrections fallback opendata & tests

---

scraper/keldoc/keldoc.py
scraper/keldoc/keldoc_center.py
tests/test_keldoc.py

2 modifications afin de moins stresser l'api keldoc, suite aux conseils de notre contact chez Keldoc. Cela va aussi permettre d'éviter les timeouts pour la première modification et d'accélérer la recherche des timetables pour la seconde
- au lieu de demander les slots pour une collection d'agendas, on fait une requête par agenda. Cela fait forcément plus de requêtes mais évite les requêtes trop lourdes qui peuvent échouer
- Pour récupérer les slots, on doit préciser une fourchette de dates. La version actuelle fait une seule demande sur une fourchette de 21 jours partant du jour courant. J'ai remplacé ça par une première requête qui demande les slots du jour courant. S'il n'y a pas de dispo ce jour là on reçoit la date de la prochaine dispo. On ajuste alors la start_date à la date reçue. …

keldoc: timetables par agenda

---

scraper/keldoc/keldoc_center.py

get_timetables -> une seule requête sur 50 jours au lieu d'une première requête pour trouver le premier rdv et une seconde pour les timetables

[Keldoc] faster scrap

---

scraper/keldoc/keldoc.py
scraper/keldoc/keldoc_center.py
scraper/scraper.py

- Ajout d'un kill switch dans keldoc.py
- On repasse à une seule requête pour tous les agendas d'une motive, la requête agenda par agenda étant trop lente
- Fix #308

[Keldoc] Réactivation

---

scraper/doctolib/doctolib.py
scraper/doctolib/doctolib_center_scrap.py
scraper/maiia/maiia.py
scraper/mapharma/mapharma.py
scraper/scraper.py
tests/fixtures/doctolib/basic-booking.json
tests/fixtures/doctolib/category-booking.json
tests/fixtures/doctolib/next-slot-booking.json
tests/test_doctolib.py
utils/vmd_utils.py

Bonjour, implantation de la #287.
L'id est de la forme `f"{plateforme}{internal_id}` pour vérifier son unicité.
Il n'est en principe pas nul non plus, j'ai fait le teste et vérifié l'unicité.
Au passage, j'ai corrigé la #170 et modifié quelques fonctions se rapportant aux codes postaux pour supprimer à tous les niveaux un éventuel espace (75 005 au lieu de 75005 par exemple)

Définition d'un internal_id unique et corrections doctolib

---

scraper/doctolib/doctolib.py
scraper/pattern/scraper_result.py
tests/test_keldoc.py
tests/test_maiia.py

J'ai remarqué des erreurs sur les calculs des appointment_schedules, qui sont maintenant corrigées avec quelques petits.
1_days contient désormais uniquement les rdvs du jour courant jusqu'à 23h59, et 2_days les rdvs du jour courant et du lendemain jusqu'à 23h59 !
J'ai du faire quelques changements sur l'iterator pour aller chercher jusqu'à 49 jours :)

[Doctolib] Correction compte nombre de rendez vous et appointment_schedules + ajout 2_days

---

scraper/ordoclic.py

**Checklist**
La fonction ```parse_ordoclic_slots``` met à jour request.appointment_count maisen remplaçant la valeur existante plutôt qu'en additionnant
Cela pose un problème sur la pharma de Henin Beaumont car il y a 2 campagnes valides: AZ à 37 créneaux et Janssen à 0, du coup les 37 sont écrasés

[ORDOCLIC] Correction appointment_count à 0

---

scraper/doctolib/doctolib.py
scraper/export/export_merge.py
scraper/scraper.py
tests/test_scraper.py

J'ai fait en sorte d'éviter de consommer l'itérateur des centres recherchés pour en faire un immense tableau en mémoire. Comme ça l'import et l'export se font en simultané et (normalement) de manière un peu efficace en mémoire.

Faire vraiment l'import export en parallèle.

---

scraper/doctolib/doctolib_center_scrap.py

**Checklist**
Remplace les urls de type partners.doctolib.fr par www.doctolib.fr

[DOCTOLIB] Fix #390 , retrait des adresses Doctolib partners

---

scraper/main.py

**Checklist**
`scrape_debug()` takes a list of url, and was given one url from `argparse`.
This commit adds support for multiple `--url` cli arguments, fixing the type bug at the same time.

Fix scraper --url, accept multiple --url

---

pyproject.toml

L'objectif de cette PR est d'ajouter un fichier de configuration pour `black`, en particulier pour configurer la taille de ligne qui n'est pas celle par défaut et qui oblige actuellement à lancer `black` avec des options.

Ajout de fichier de config pour black

---

scraper/keldoc/keldoc_center.py

**Checklist**
On a beaucoup de timeout, je propose de limiter la recherche d'agendas à 2 pages soit 10 jours au moins pour aujourd'hjui qui va être une journée très chargée

[Keldoc] Réduction du scrape à 10 jours

---

scraper/ordoclic.py
tests/fixtures/ordoclic/search.schema
tests/test_ordoclic.py
utils/vmd_utils.py

**Checklist**
Suite à une mise à jour de l'API Ordoclic, les paramètres de la recherche des centres ont changé et plus aucun centre Ordoclic ne remonte de l'iterator

[Ordoclic] Mise à jour du filtre de recherche

---

Makefile
config.json
stats_generation/by_vaccine.py
tests/stats_generation/test_by_vaccine.py

**Checklist**
Ajoute un script qui compte les rendez-vous disponibles par type de vaccin.
Note : Certains centres (~10%) listent plusieurs types de vaccins. Dans ces cas là, la répartition par vaccin n’est pas claire, alors je les ai laissés de côté pour l’instant.
Si quelqu’un sait faire autrement, qu’il se manifeste :D

Add a script to count appointments per vaccine type

---

scraper/doctolib/doctolib_center_scrap.py

**Checklist**
[On a fait un scrap de centres qui est passé avec seulement 4 départements avant de se faire 403 par Doctolib](https://github.com/CovidTrackerFr/vitemadose/actions/runs/840112430). Du coup, le site n'a pas eu tous les centres pendant 30+ minutes et a été hot-fix par une intervention sur le code. Ce fix devrait empêcher ce problème dans le futur.

Empêche les pushes de mauvais scraps de centres doctolib

---

scraper/doctolib/doctolib_center_scrap.py

**Checklist**
@aureliancnx avait ré-inversé l'override des données du centre. C'est bien la browse_page qu'on utilise par défaut, et qu'on enrichie avec les info_centers si disponible. J'ai rajouté un commentaire pour ne pas que çela soit changé

Deduplicate noms centres quand même sous-centres

---

scraper/mapharma/mapharma.py
tests/test_mapharma.py

**Checklist**
Certaines campagnes mapharma ont des créneaux disponibles sur l'API mais non affichés sur leur site. Ce sont en fait des calendriers qui sont en attente de réception de vaccins et donc il ne faut pas les afficher comme disponibles
On cherche donc la campagne dans l'opendata pour vérifier total_libres. Si sa valeur est nulle on arrête le fetch_slot et on renvoie None, sinon on va parser les agendas

[Mapharma] filtre total_libres = 0

---

scraper/doctolib/doctolib.py
scraper/pattern/scraper_request.py
scraper/scraper.py
tests/test_center_info.py
tests/test_doctolib.py
tests/test_doctolib_scraper.py
tests/test_mapharma.py
tests/test_scraper.py

Deuxième partie de l'optimisation des requêtes avec Doctolib. J'ai ajouté la possibilité d'envoyer des données en "input" au fetch_slots (qui est utile en l'occurrence pour les données de l'endpoint booking). Ca permet d'envoyer les données de la requête 'booking' que l'on fait dans le scraper Doctolib (et qui est dans le JSON du scraper).
Ca permet de ne plus utiliser l'endpoint booking à chaque fois que l'on fetch les créneaux sur les centres /!\
Actuellement, en utilisant l'endpoint `requests` à chaque scrape des créneaux (nombre de requêtes) : 
```
+----------+-------+------------+----------+---------+---------+----------+-------+
| Platform | Total | next-slots | resource | booking | motives | cabinets | slots | …
```

Use booking input data for Doctolib rdv

---

config.json

J'ai scrapé l'ensemble des centres sur doctolib, et regardé les vaccination_motive = True pour lesquels nous avions is_category_relevant = False
J'ai regardé à la main tous ces motifs, et j'ajoute donc ceux qui manquent actuellement :)
Du coup, on devrait récupérer pas mal de centres qui manquaient !!

[DOCTOLIB] - Ajout de motifs manquants

---

tests/test_utils.py
utils/vmd_utils.py

Les numéros de téléphone de AvecMonDoc sont préfixés par `00`, qui est le [préfixe vers les appels internationaux standard](https://fr.wikipedia.org/wiki/Indicatif_t%C3%A9l%C3%A9phonique_international). Notre fonction `format_phone_number()` ne savait pas gérer ce préfixe, cette PR corrige le problème.
cc @gaelbenoit

utils: accept phone numbers with international prefix '00'

---

.gitlab-ci.yml
scripts/create-index.sh

On dit beaucoup sur internet que nos données sont ouvertes, mais on ne référence sur data.gouv.fr qu'une seule ressource parce que c'est celle dont on est à peu près sûr qu'on va pas la casser.
Cette PR liste tous les JSON disponibles dans le dossier `/data/output` qui se retrouvent publiés dans un fichier index.html qui sera servi par défaut sur https://vitemadose.gitlab.io/vitemadose
c'est du bash-fu assez basique, mais grosso modo ça fait un `find -name '*.json'` et ça transforme la liste en `<ul> <li/> × 1000 </ul>`

Génère un fichier index.html qui référence les JSON exposés

---

scraper/avecmondoc/avecmondoc.py
tests/test_avecmondoc.py
tests/test_doctolib_scraper.py

le format du prochain rdv pose un problème de décalage GMT sur l'app Android
j'en profite pour fixer:
- le timeout pas pris en compte
- forcer l'encodage utf8 qui fait planter les tests sous Windows

[AvecMonDoc] date prochain rdv en GMT+2

---

scraper/pattern/center_info.py
scraper/pattern/scraper_request.py

On a fait des changements sans trop prévenir pour le type de vaccin. On renvoie dans le JSON désormais une liste vide si aucun type de vaccin n'a été trouvé, sauf que ça créé un problème au niveau de l'icône du type de vaccin sur l'application iOS, elle est quand-même affichée.
En attendant qu'un fix soit fait au niveau d'iOS et que ça passe en review tout ça tout ça, je me permets de remettre comme c'était à ce niveau.

Hotfix vaccine type icon shown if it's an empty list on iOS

---

scraper/avecmondoc/avecmondoc.py
tests/test_avecmondoc.py

2ème fix pour avoir une heure correcte en retour, les heures de rendez-vous sont en fait renvoyés en UTC
j'en profite pour gérer les heures de rdv au format datetime et pas str

[AvecMonDoc] utc timezone

---

scraper/circuit_breaker.py
scraper/keldoc/keldoc.py
scraper/keldoc/keldoc_center.py
scraper/scraper.py
setup.py
tests/test_circuit_breaker.py
tests/test_keldoc.py

**Checklist**
Un peu en rapport avec #368 et #445 
J'ai appliqué le pattern [_Circuit Breaker_](https://blog.octo.com/circuit-breaker-un-pattern-pour-fiabiliser-vos-systemes-distribues-ou-microservices-partie-2/) (désolé pour le lien corporate, mais c'est mon premier résultat google) sur la fonction `fetch_slot` du module Keldoc.
Le principe est de comptabiliser les excecution "erronée" (ici, temps trop long) et de couper l'accès à ce chemin d'exécution complètement pour un certain temps (ici un certain nombre de tentatives).
Les nombres sont évidemment à ajuster. Un effet de bord "sympa" c'est que ça limite le nombre de processus qui sont effectivement en train de faire des appels à Keldoc à la valeur du paramètre `trigger`.
Les tests Sur Ma Machine™ montrent que c'est …

Mettre Keldoc au coin quand il ne répond pas assez rapidement 🦆

---

data/input/centers_blocklist.json

La pharmacie est sur ordoclic et doctolib et ne veut pas être référencée via ordoclic.

Ajout Captain Pharma (Nanterre) Ordoclic à blocklist

---

scraper/doctolib/doctolib_center_scrap.py
scraper/doctolib/doctolib_parsers.py
tests/fixtures/doctolib/scrap-center-result.json
tests/test_doctolib_scraper.py

**Checklist**
Refact de doctolib center scrap pour avoir une structure similaire au scraper principal de doctolib, qu'on peut faire tourner sur un mock dans les tests.

Allow doctolib center scrap to run on fake client

---

scraper/maiia/maiia_utils.py

On voit des timeouts dans les logs du scrape Maiia, ce qui semble montrer que le timeout par défaut n'est pas suffisant, je propose donc de le réactiver

[Maiia] Réactivation du timeout

---

tests/test_geo_api.py
utils/vmd_geo_api.py

Ajout de fonctions pour appeler les endpoints search/ and reverse/ de [API Adresse](https://geo.api.gouv.fr/adresse). C'est en prévision de l'ajout de Clikodoc, les adresses sont de mauvaises qualités (adresse avec code postal, adresse avec code postal et commune, adresse en majuscule). A fortiori, on pourrait utiliser ces appels pour toutes les plateformes, la limite est à 50 appels par secondes et IP. 
Il y a apparemment un soucis sur l'API search/ parce que l'aide à la localisation avec des coordonnées ne donnent pas de bons résultats (cf. le test qui échoue), je vais essayer de remonter le problème, dans le pire des cas, j'enlèverai cette option

Ajout d'helper pour API Adresse

---

scraper/export/export_v2.py
scraper/export/resource_centres.py
scraper/export/resource_creneaux_quotidiens.py
scraper/scraper.py
utils/vmd_utils.py

**Checklist**
Permet de limiter la quantité de CPU utilisé lors de l'export des données afin que la rapidité de la consommation ne soit pas un facteur limitant pour écrire dans la file.
D'autre part, les éléments de la file sont envoyé en lot (bulk) pour limiter l'utilisation d'I/O, c'est possible car l'ordre n'est pas important.
Voici le flamegraph de du processus de l'export après optimisations
A comparer à avant :
On voit que plus de temps est passé à effectivement traiter la donnée plutôt qu'à l'attendre.
On gagne un peu plus d'une minute de temps d'execution 
Avec : https://gitlab.com/ViteMaDose/vitemadose-staging/-/jobs/1316400295
Sans : https://gitlab.com/ViteMaDose/vitemadose-staging/-/jobs/1309954501

Ajustements pour la performance avec les Creneaux

---

gitlab-runner/envs/terragrunt.hcl
gitlab-runner/modules/runner/main.tf
gitlab-runner/modules/runner/provision.sh
gitlab-runner/modules/runner/variables.tf

La documentation de l'installation datadog de l'agent se trouve ici:
https://docs.datadoghq.com/getting_started/agent/
Le code est disponible ici 
https://s3.amazonaws.com/dd-agent/scripts/install_script.sh
Je suppose que `DD_API_KEY` est injecté à la main et peut être trouvé là https://app.datadoghq.com/account/settings#api. Il faut prendre la clé `GitLab Runner`.
D'autres PR pourront suivre pour la configuration de l'agent (collecte des logs, tags, etc.) pour l'instant j'essaye juste d'avoir un agent fonctionnel qui remonte des métriques.

Installation de l'agent Datadog dans les runners gitlab

---

scraper/doctolib/doctolib.py
scraper/error.py
scraper/export/export_merge.py
scraper/export/export_pool.py
scraper/scraper.py
tests/fixtures/doctolib/basic-booking.json
tests/fixtures/doctolib/category-booking.json
tests/fixtures/doctolib/next-slot-booking.json
tests/test_doctolib.py
tests/test_scraper.py

**Checklist**
- [424, 490, 495 ] Fix #issue
Gestion des doublons pour Doctolib.
En gros, dans la page booking/centre.json, il faut vérifier que dans l'agenda en cours, le pid du centre est bien dans les keys de visit_motive_ids_by_practice_id 
Par exemple, admettons que notre pid soit 125410, si l'agenda en cours de la page booking contient `"visit_motive_ids_by_practice_id":{"164604":[2548342,2548343]}`, c'est que le centre 125410 est un ancien centre qu'il ne faut pas mettre dans les json.
Ce centre finit par disparaitre de la page vaccination-covid-19/departement.json mais cela met plusieurs jours voir semaines, d'où ma solution pour éviter les centres en quadruple (en sachant qu'il y a pas mal de centres temporaires qui ne sont là que pour quelques jours !)
@Floby …

[Doctolib] - Gestion des doublons

---

scraper/doctolib/doctolib_center_scrap.py

Le Doctolib Center Scrap pose soucis depuis quelques heures, j'ai rajouté le statuscode de la requete dans le logger pour pouvoir débug.

[Doctolib Center Scrap] - Add traceback for debug

---

utils/vmd_utils.py

- remove the useless lookbehind assertion (since there's a capture group to extract the city)
- reach the postal code position more quickly from the start of the string with `\D+`
- more flexible with spaces between the postal code and the city `\s` => `\s+`
- change the reluctant quantifier to a greedy one followed by a non-space character `.*?` => `.*\S` 
test: https://regex101.com/r/cMq1Oq/1
**Checklist**

get_city():  Pattern improvement

---

README.md

**Checklist**
L’URL du logo de Bimedoc dans le README n’est actuellement pas correcte, elle cause une erreur 404. Cette PR corrige cela.

Correction du logo Bimedoc sur le README

---

config.json
tests/test_doctolib.py

Currently, we are targetting API by 7 days requests.
It is now possible to target by 14 days range, and it's exactly what I did !
We won 2k requests on each scrape with the same results.

[Doctolib] - Increasing Days Per Page

---

config.json
scraper/doctolib/doctolib.py

Pour répondre aux besoins de santé.fr, mise en place pour Doctolib (dans un 1er temps) d'un filtre "scrape_only_atlas_centers" dans config.json

[Scraper] - Filtre only AtlasSanté

---

config.json
tests/test_doctolib.py

Au vu du fonctionnement de doctolib (reservation de la 2e dose lors de la prise de rdv pour la 1ère), il n'est pas nécessaire de scraper les 2e doses. Cette amélioration vise à l'accélération du temps de scrape.

[doctolib] - Retrait 2e doses

---

scraper/doctolib/doctolib.py

**Checklist**
Sur Doctolib, le `practice_id`soit depuis l'URL soit depuis le champ `places` de l'API booking. Dans le second cas, le cas actuel ne gérait pas le cas où `places` ne contenait qu'un seul élément, `practice_id` restait à None et le scrape crashait plus loin quand on essaye d'itérer sur `None` (c'est un autre bug à corriger ça), résultat le centre n'apparaît pas dans la sortie du scrape. Il y a au moins deux centres concernés (cf les issues) mais je pense qu'il y a en a bien plus en pratique.

Extraire correctement le practice_id de "places" avec Doctolib

---

config.json
scraper/avecmondoc/avecmondoc.py
tests/test_avecmondoc.py

**Checklist**
Le rang d'injection n'est pas détecté par le scraper AvecMonDoc. Du coup le front-end qui filtre part rang d'injection connu n'affiche plus les créneaux disponibles car ils ne sont pas associés à un rang d'injection. J'ai donc ajouté la détection du rang en fonction du motif (Première injection, Deuxième injection, Troisième injection), tout en ajoutant les deuxièmes et troisièmes injection comme motifs valides dans le fichier config.json

Prise en compte du rang d'injection pour AvecMonDoc

---

scraper/doctolib/doctolib_center_scrap.py
scraper/keldoc/keldoc_center_scrap.py
scraper/mesoigner/mesoigner_center_scrap.py

**Checklist**
Actuellement les scraps de centres de certaines plateformes retourne un code d'erreur 0 en cas d'un nombre insuffisant de centres (voire même pas de centre du tout), par conséquent, la CI pense que la tâche a fini avec succès (cf ce job https://github.com/CovidTrackerFr/vitemadose/runs/4914359773?check_suite_focus=true). Avec un exit code à 1, le job remontera correctement un échec.

Retourner un exit code d'erreur en cas d'échec du scrap de centres
